### ISSUE TITLE
Custom group order 

### ISSUE THREAD

**Issue by JIAZoro** [Dimibe/grouped_list#32]
怎么对组进行自定义排序？
比如例子中的是[Team A,Team B, Team C],
如果要按照[Team C,Team A,Team B]该怎么做？

**Comment by Dimibe** [comment]
@JIAZoro Could you please translate it english otherwise I can't help you.

**Comment by JIAZoro** [comment]
How to customize the order of the groups?
Your Demo the  order of the group is [Team A, Team B, Team C,Team D],
if the custom order of group is [b,a,d,c],how to do?

**Comment by Dimibe** [comment]
@JIAZoro I don't know your data structure used for the list but if your elements are objects the easiest solution is to implement the Comparable interface so that your elements get sorted like you want. Then you would have also the whole object for the groupSeparator where you could extract the group header information from.  

So something like this for your data structure: 
```
class Element implements Comparable {
  final String groupHeader;
  final String groupIndex;

  Element(this.groupHeader, this.groupIndex);

  @override
  int compareTo(other) {
    return groupIndex.compareTo(other.groupIndex);
  }
}
```
and then the List config: 
```
 groupBy: (element) => element,
 elements: _elements,
 groupSeparatorBuilder: (Element element) => Text( element.groupHeader),
```

Let me know if that solves your problem.

**Comment by JIAZoro** [comment]
This problem has been solved by adding Index to the data。
thank you
