### ISSUE TITLE
Request for Feature: different values for 'groupBy' and 'groupSeparatorBuilder()'

### ISSUE THREAD

**Issue by deezaster** [Dimibe/grouped_list#47]
Current example:

groupBy = yyyyMMdd (e.g. 20200409)
groupSeparatorBuilder() = yyyy MMM (e.g. 2020 April)

In this example (order: GroupedListOrder.DESC) Mai (engl. May) should be before März (engl. March):

![image](https://user-images.githubusercontent.com/1539838/84814000-1b77f380-b011-11ea-957e-77b12d7c19f9.png)

Request:
It would be nice to pass the entire map (the element) to the function 'groupSeparatorBuilder()', instead the value from the groupBy.

**Comment by Dimibe** [comment]
Hi @deezaster, there were several questions like yours, but I have some concerns because of backwards compatibility. I'm trying to provide an easy solution for this in the future. Currently there is a work around which you can try (only works if your data are real objects): 

1.  Group by the element itself then the element will available in the groupSeparator function.
2. Override the `compareTo` method in your element's class and group by the value you like.

Code from the Widget: 
```dart
GroupedListView<Element, Element>(
          elements: _elements,
          groupBy: (element) => element,
          groupSeparatorBuilder: (Element element) => Text(
            element.groupName,
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
          ),
          [...]
),
```

Code from the elements class: 
```dart
class Element implements Comparable {
  String groupName;
  int groupIndex;
  String name;

  Element(this.groupIndex, this.groupName, this.name);

  @override
  int compareTo(other) {
    int compareResult = groupIndex.compareTo(other.groupIndex);
    // if result is 0 both items are in the same group, so sort them according their name.
    if (compareResult == 0) {
      compareResult = name.compareTo(other.name);
    }
    return compareResult;
  }

  @override
  bool operator ==(Object other) => other is Element && other.groupIndex == groupIndex;

  @override
  int get hashCode => groupIndex.hashCode;
}
```

The data for the list widget: 
```dart
List _elements = <Element>[
  Element(1, 'Team One', 'John'),
  Element(2, 'Team Two', 'Will'),
  Element(1, 'Team One', 'Beth'),
  Element(2, 'Team Two', 'Miranda'),
  Element(3, 'Team Three', 'Mike'),
  Element(3, 'Team Three', 'Danny'),
];
```
The result: 
![image](https://user-images.githubusercontent.com/15692917/84882628-d2b34f80-b08f-11ea-9cd1-e6bd84d86dbd.png)

I aware this is not a small solution but currently the only one which solves your request. 

Hopefully this will help you 

Best regards

**Comment by Dimibe** [comment]
@deezaster I've created a new package which depends on scrollable_positioned_list. In this package the groupSeparatorBuilder takes the whole element as argument. 
Maybe you want to try it out: https://github.com/Dimibe/sticky_grouped_list
