### ISSUE TITLE
Custom Ordering as Enhancement

### ISSUE THREAD

**Issue by jadenwjh** [Dimibe/grouped_list#48]
Perhaps it will be a good idea to have a way to have custom orderings? This will allow different groups to be flushed to the top of the list, which is a feature I noticed is lacking in many widgets

**Comment by Dimibe** [comment]
Hi @jadenwjh, 
what would you expect for an custom ordering? If you have any ideas please let me know.

Maybe this helps already a bit:
 I have made another grouped list package where the groupSeparatorBuilder gets the whole element instead of just the `groupBy` value. E.g. with that it's possible to display weekdays as groups names and sort them so that Monday is always on top (#47) . 

I've created the new package because 
- it builds on scrollable_positioned_list and 
- performance with sticky headers is better

Check it out: https://github.com/Dimibe/sticky_grouped_list

**Comment by jadenwjh** [comment]
Hi @Dimibe , I really liked the sticky_grouped_list. Thanks for sharing.

The custom ordering i was referring to was something like this:

I have different groups of items (Monday Tuesday ....). By default, Monday will be pushed to the top of the list. I am looking for a way to modify this order. For example, once it is Tuesday, I would like Monday to go to the bottom, and Tuesday to be pushed to the top. 

That being said, I will be trying this out with the sticky grouped list as I think that is doable using DateTime. However, it might not apply if the groups are items with String names.

**Comment by pratamatama** [comment]
Hi @Dimibe , I agree with this enhancement request. There is an issue when using the ordering when the data is already sorted from the backend.

To be clear, please have a look at the screenshot below. On the left, it shows the original data sorted by the latest creation date to the oldest and `GroupedListOrder` set to `ASC`. The grouping is fine, but it doesn't put Today's data on first position of group list.

Though, it got solved by setting the `GroupedListOrder` to `DESC` but there is another problem (see screenshot on the right). Today's data is comes first, but the order is flipped. In this case, "Test background fetch 10" must be at the beginning of the list. It would be nice if there is a feature to customize the ordering manually, so how do you think?

![image](https://user-images.githubusercontent.com/42239243/91912046-7f3ebe00-ecdc-11ea-9358-cb107cf86fc7.png)

**Comment by Dimibe** [comment]
Done with #59
