### ISSUE TITLE
Render items even if not shown on screen

### ISSUE THREAD

**Issue by jadenwjh** [Dimibe/grouped_list#54]
Hi, the issue is regarding the use of Builder. The items that are not mounted on the screen will not be render, unless the user manually scrolls the the list to reveal them. This is an issue because in my app, the items have Timers and the Timers in the items far down the list cannot be activated unless the user scrolls the list.

**Comment by jadenwjh** [comment]
I figured out a workaround for the problem. That is to programmatically scroll the list once the list is built, before the user can interact with it. This can be a small addition to the widget i feel.

@override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _controller.jumpTo(_controller.position.maxScrollExtent);
      _controller.jumpTo(_controller.position.minScrollExtent);
    });
  }

**Comment by Dimibe** [comment]
Hi @jadenwjh, 
this behavior is by design done in the ListView.builder. It allows you to pass many data in the list without the list beeng laggy because rendering the items is expensive. For that I will not change the widget. I think your use case is a special one and implementing this will cause performance issues for many other use cases.

**Comment by Syetchau** [comment]
Hi, I had implement this library in my project and used it to display list of data. When I switched index of chips, the list would filtered and rebuild the widget. It seem that rendering the huge list of data would take some time for the UI to built completely and causing poor performance. Is there any ways to overcome this issue ?
