### ISSUE TITLE
groupSeparatorBuilder ignored if groupHeaderBuilder is used

### ISSUE THREAD

**Issue by xJon** [Dimibe/grouped_list#63]
`groupSeparatorBuilder` is useful for simple padding between groups; when using only `groupHeaderBuilder`, the first group also gets top padding, which isn't ideal.

**Comment by Dimibe** [comment]
@xJon As written in the readme it is designed so that the groupSeparatorBuilder gets ignored when the groupHeaderBuilder is used. The two methods should do exactly the same, the only difference is the passed parameter to the builder. If there is any issue please provide an small example where the two functions lead to a different result.

**Comment by xJon** [comment]
I want to simply place padding between each group, what do you think would be the best way to do so?
As I wrote before, I can't add top padding to each group header as I don't want the top (first) group header to have top padding.

**Comment by Dimibe** [comment]
@xJon I think the only way is to check inside the builder if it's the first group and if so don't set the heading. This is a dirty solution because no index is provided and you need to figure out yourself if it's the first group or not. 

What I don't get is what this issue has to do with the two different builder functions. They should work the same and it should be the same no matter which you use.

**Comment by xJon** [comment]
`groupSeparatorBuilder` sounds like it could work differently because of `Separator`, I didn't realize they work exactly the same.

**Comment by nikola-flair** [comment]
Group separator is at the bottom of the group, group header is at top. That's how it should be. I don't really understand why would it be ignored. How can I know if the item is last item in that group?
