### ISSUE TITLE
Bug: Latest update (3.7.1) not compiling

### ISSUE THREAD

**Issue by MilesZoltak** [Dimibe/grouped_list#76]
There seems to be a problem with "clipBehavior", reverting to 3.5.0 (just chose that one bc it was the version i started with) makes it work just fine in the meantime.

**Comment by Dimibe** [comment]
Hi @MilesZoltak could you please further elaborate what error do you get? And what version of flutter and dart you are using. 

For me everything works fine so I need more information.

**Comment by abdulpiksi** [comment]
same as me

**Comment by Dimibe** [comment]
Hi @abdulpiksi, thanks for the detailed information. I see that you are using Flutter version 1.20. 
The latest stable version is currently 1.22.4. 
You will need to upgrade to Flutter version 1.22 in order to solve the error. 

@MilesZoltak I think you have the same error then. 

Sorry for the inconvenience.
